@startuml  diagrama-entidad-relacion-BI.

/'
    Aclaraciones:
        - Considere no poner la palabra "dimensión" en los nombres de las tablas (por ejemplo, usar solo "tiempo" en lugar de "dimensión_tiempo"). Esto hace los nombres más cortos y claros. Además, el diagrama permite identificar fácilmente qué tablas son hechos y cuáles son dimensiones.

        - La consigna dice: "Se deberán considerar como mínimo las siguientes dimensiones, además de las que el alumno considere convenientes." Por eso, probablemente tengamos que agregar más dimensiones o hechos, o tal vez más atributos en algunas dimensiones.

        - Para avanzar, usé:
            - https://raw.githubusercontent.com/sebastiangilberto/utn-gdd-2c2022-tp/main/tp/der/der_BI.svg
            - Las diapositivas del profesor sobre el modelo de estrella, OLAP y DataWarehouse.

        - No estoy seguro sobre el rango horario y el rango etario. Puede que queden bien como están, tener un atributo para cada tipo o quizas se les ocurra otra idea.

        - Acuerdense de que los tipos datos deben ser los mismos de la tabla principal: "Todas las columnas creadas para las nuevas tablas deberán respetar los mismos tipos de datos de las columnas existentes en la tabla maestra."

        - Tengo dudas sobre si el "producto" debería ser un hecho o una dimensión, o si puede ser ambas cosas en distintas tablas. La misma duda tengo con "publicación".
'/


'----------------------------------
'---------- HECHO VENTA -----------
'----------------------------------

entity "hecho_venta" {
  * hechoVenta_tiempo_id: INT **<<PK, FK>>**
  * hechoVenta_ubicacionAlmacen_id: INT **<<PK, FK>>**
  * hechoVenta_ubicacionCliente_id: INT **<<PK, FK>>**
  * hechoVenta_rubro_id: INT **<<PK, FK>>**
  * hechoVenta_rangoEtario_id: INT **<<PK, FK>>**
  --
    * hechoVenta_valorPromedio: DECIMAL(18, 2)
    * hechoVenta_cantidadVentas: INT
    * hechoRubro_totalVentas: DECIMAL(18, 2)
}

entity "tiempo" {
  * tiempo_id: INT **<<PK>>**
  --
    * tiempo_anio: INT  
    * tiempo_cuatrimestre: INT
    * tiempo_mes: INT
}

entity "ubicacion" {
  * ubicacion_id: INT **<<PK>>**
  --
    * ubicacion_localidad_id: INT
    * ubicacion_localidad_nombre: NVARCHAR(50)
    * ubicacion_provincia _id: CHAR(2)
    * ubicacion_provincia_nombre: NVARCHAR(50)
}

entity "rango_etario_cliente" {
  * rangoEtarioCliente_id: INT **<<PK>>**
  --
    * rangoEtarioCliente_nombre: NVARCHAR(16)
}
note bottom
    Rangos etarios: 
        - JUVENTUD: < 25
        - ADULTEZ_TEMPRANA: [25, 35)
        - ADULTEZ_MEDIA: [35, 50]
        - ADULTEZ_AVANZADA: > 50
end note


entity "rubro" {
  * rubbro_id: INT **<<PK>>**
    * hechoRubro_nombre: NVARCHAR(50)
}

hecho_venta -- "tiempo"
hecho_venta -- "ubicacion"
hecho_venta -- "rango_etario_cliente"
hecho_venta -- "rubro"


'----------------------------------
'------- HECHO PUBLICACION --------
'----------------------------------

entity "hecho_publicacion" {
  * hechoPublicacion_tiempo_id: INT **<<PK, FK>>**
  * hechoPublicacion_subrubro_id: INT **<<PK, FK>>**
  * hechoPublicacion_marca_id: INT **<<PK, FK>>**
  --
    * hechoPublicacion_diasPromedioVigente: DECIMAL(10, 2)
    * hechoPublicacion_cantidadStockPromedio: DECIMAL(18, 2)
}

entity "subrubro" {
  * subrubro_id: INT **<<PK>>**
  --
    * subrubro_rubro: NVARCHAR(50)
    * subrubro_subrubro: NVARCHAR(50)
}

entity "marca" {
  * marca_id: INT **<<PK>>**
  --
    * marca_nombre: NVARCHAR(50)
}

entity "tiempo " {
  * tiempo_id: INT **<<PK>>**
  --
    * tiempo_anio: INT  
    * tiempo_cuatrimestre: INT
    * tiempo_mes: INT
}

hecho_publicacion -- "tiempo "
hecho_publicacion -- "subrubro"
hecho_publicacion -- "marca"


'----------------------------------
'----------- HECHO PAGO -----------
'----------------------------------

entity "hecho_pago" {
  * hechoPago_tipoMedioPago_id: INT **<<PK, FK>>**
  * hechoPago_tiempo_id: INT **<<PK, FK>>**
  * hechoPago_ubicacionCliente_id: INT **<<PK, FK>>**
  --
    * hechoPago_importeTotalCuotas: DECIMAL(18, 2)
}

entity "tipo_medio_pago" {
  * tipoMedioPago_id: INT **<<PK>>**
  --
    * tipoMedioPago_nombre: NVARCHAR(50)
}

entity "tiempo   " {
  * tiempo_id: INT **<<PK>>**
  --
    * tiempo_anio: INT  
    * tiempo_cuatrimestre: INT
    * tiempo_mes: INT
}

entity "ubicacion  " {
  * ubicacion_id: INT **<<PK>>**
  --
    * ubicacion_localidad: NVARCHAR(50)
    * ubicacion_provincia: NVARCHAR(50)
}

hecho_pago -- "tipo_medio_pago"
hecho_pago -- "tiempo   "
hecho_pago -- "ubicacion  "


'----------------------------------
'--------- HECHO FACTURA ----------
'----------------------------------

entity "hecho_factura" {
  * hechoFactura_tiempo_id: INT **<<PK, FK>>**
  * hechoFactura_concepto_id: INT **<<PK, FK>>**
  * hechoFactura_ubicacionVendedor_id: INT **<<PK, FK>>**
  --
    * hechoFactura_porcentajeFacturacion: DECIMAL(18, 2)
    * hechoFactura_montoFacturado: DECIMAL(18, 2)
}

entity "concepto" {
  * concepto_id: INT **<<PK>>**
  --
    * concepto_nombre: NVARCHAR(50)
}

entity "tiempo     " {
  * tiempo_id: INT **<<PK>>**
  --
    * tiempo_anio: INT  
    * tiempo_cuatrimestre: INT
    * tiempo_mes: INT
}

entity "ubicacion    " {
  * ubicacion_id: INT **<<PK>>**
  --
    * ubicacion_localidad: NVARCHAR(50)
    * ubicacion_provincia: NVARCHAR(50)
}

hecho_factura -- "tiempo     "
hecho_factura -- "concepto"
hecho_factura -- "ubicacion    "


'----------------------------------
'---------- HECHO ENVIO -----------
'----------------------------------

entity "hecho_envio" {
  * hechoEnvio_tiempo_id: INT **<<PK, FK>>**
  * hechoEnvio_ubicacionAlmacen_id: INT **<<PK, FK>>**
  * hechoEnvio_tipoEnvio_id: INT **<<PK, FK>>**
  --
    * concepto_porcentajeCumplimiento: DECIMAL(18, 2)
}

entity "tiempo      " {
  * tiempo_id: INT **<<PK>>**
  --
    * tiempo_anio: INT  
    * tiempo_cuatrimestre: INT
    * tiempo_mes: INT
}

entity "ubicacion     " {
  * ubicacion_id: INT **<<PK>>**
  --
    * ubicacion_localidad: NVARCHAR(50)
    * ubicacion_provincia: NVARCHAR(50)
}

entity "tipo_envio" {
  * tipoEnvio_id: INT **<<PK>>**
  --
    * tipoEnvio_nombre: NVARCHAR(50)
}

hecho_envio -- "tiempo      "
hecho_envio -- "ubicacion     "
hecho_envio -- "tipo_envio"


'----------------------------------
'--------- HECHO LOCALIDAD --------
'----------------------------------

entity "hecho_localidad" {
  * hechoLocalidad_ubicacionCliente_id: INT **<<PK, FK>>**
  --
    * hechoLocalidad_costoEnvio: DECIMAL(18, 2)
}

entity "ubicacion      " {
  * ubicacion_id: INT **<<PK>>**
  --
    * ubicacion_localidad: NVARCHAR(50)
    * ubicacion_provincia: NVARCHAR(50)
}

hecho_localidad -- "ubicacion      "

@enduml 